project:
  type: book
  output-dir: docs

book:
  title: "Avaliação da Funcionalidade do Solo"
  subtitle: "Sistemas de Manejo Agrícola Usando Lógica Fuzzy"
  author: "Diego et al."
  date: today
  favicon: cover.png
  cover-image: cover.png
  downloads: pdf
  reader-mode: true
  sidebar:
    align: left
    collapse-level: 1
  
  chapters:
    - index.qmd
    - text: "Introdução"
      file: chapters/01-introduction.qmd
    - text: "Metodologia"
      file: chapters/03-methodology.qmd
    - text: "Resultados e Discussão"
      file: chapters/04-results.qmd
    #- text: "Discussão"
    #  file: chapters/05-discussion.qmd
    - text: "Conclusão"
      file: chapters/06-conclusion.qmd
    - references.qmd

execute:
  freeze: auto

format:
  html:
    title-block-style: none
    theme:
      light: flatly
      dark: darkly
    toc: true
    toc-depth: 3
    number-sections: true
    code-fold: false
    code-overflow: wrap
    link-external-newwindow: true
    html-math-method: mathjax
    
  pdf:
    documentclass: article
    number-sections: true
    code-overflow: wrap
    geometry:
      - top=2.5cm
      - bottom=2.5cm
      - left=2.5cm
      - right=2.5cm

bibliography: references.bib
csl: apa.csl
